import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialAlpenSchema1753003888780 implements MigrationInterface {
    name = 'InitialAlpenSchema1753003888780'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "route_fares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_location" character varying NOT NULL, "from_country_code" character varying(2) NOT NULL, "to_location" character varying NOT NULL, "to_country_code" character varying(2) NOT NULL, "distance_km" integer NOT NULL, "vehicle" character varying NOT NULL, "min_fare" numeric(10,2) NOT NULL, "original_fare" numeric(10,2) NOT NULL, "sale_fare" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'EUR', "is_active" boolean NOT NULL DEFAULT true, "effective_from" TIMESTAMP NOT NULL DEFAULT now(), "effective_until" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_426fba162ed7ece39d288cc2ccd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_categories_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "car_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "base_rate" numeric(10,2) NOT NULL, "per_km_rate" numeric(10,2), "per_minute_rate" numeric(10,2), "max_passengers" integer NOT NULL, "status" "public"."car_categories_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cdc0a8872ec123a3b7bdfd389d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_images_image_type_enum" AS ENUM('exterior', 'interior', 'features')`);
        await queryRunner.query(`CREATE TABLE "car_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "car_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "image_type" "public"."car_images_image_type_enum" NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, "alt_text" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7870496c0b0f5a8894cab2bde3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reviews_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "overall_rating" integer NOT NULL, "punctuality_rating" integer, "cleanliness_rating" integer, "comfort_rating" integer, "review_text" text, "status" "public"."reviews_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_bbd6ac6e3e6a8f8c6e0e8692d6" UNIQUE ("booking_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_background_check_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "company_id" uuid, "license_number" character varying NOT NULL, "license_expiry" date NOT NULL, "date_of_birth" date NOT NULL, "address" text, "city" character varying, "state" character varying, "postal_code" character varying, "emergency_contact_name" character varying, "emergency_contact_phone" character varying, "profile_photo_url" character varying(500), "background_check_status" "public"."drivers_background_check_status_enum" NOT NULL DEFAULT 'pending', "medical_clearance" boolean NOT NULL DEFAULT false, "training_completed" boolean NOT NULL DEFAULT false, "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_rides" integer NOT NULL DEFAULT '0', "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_47543bd8e5e11a094ded9a56e98" UNIQUE ("license_number"), CONSTRAINT "REL_8e224f1b8f05ace7cfc7c76d03" UNIQUE ("user_id"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."driver_car_assignments_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "driver_car_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "car_id" uuid NOT NULL, "assigned_date" TIMESTAMP NOT NULL DEFAULT now(), "unassigned_date" TIMESTAMP, "is_primary" boolean NOT NULL DEFAULT false, "status" "public"."driver_car_assignments_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "UQ_bfa8041cd24000e9c466dc5a32b" UNIQUE ("driver_id", "car_id", "assigned_date"), CONSTRAINT "PK_3874df5c6d308bb8762b186ecf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cars_status_enum" AS ENUM('active', 'maintenance', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "cars" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "company_id" uuid, "make" character varying NOT NULL, "model" character varying NOT NULL, "year" integer NOT NULL, "color" character varying, "license_plate" character varying NOT NULL, "vin" character varying, "seats" integer NOT NULL, "has_medical_equipment" boolean NOT NULL DEFAULT false, "has_infant_seat" boolean NOT NULL DEFAULT false, "has_child_seat" boolean NOT NULL DEFAULT false, "has_wheelchair_access" boolean NOT NULL DEFAULT false, "has_wifi" boolean NOT NULL DEFAULT false, "has_ac" boolean NOT NULL DEFAULT false, "has_gps" boolean NOT NULL DEFAULT false, "status" "public"."cars_status_enum" NOT NULL DEFAULT 'active', "last_service_date" date, "next_service_date" date, "odometer_reading" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97deb66a03be534e7c02d9add0a" UNIQUE ("license_plate"), CONSTRAINT "UQ_1a56deecb54b4ed4917445f49e9" UNIQUE ("vin"), CONSTRAINT "PK_fc218aa84e79b477d55322271b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupon_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "coupon_id" uuid NOT NULL, "user_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "discount_applied" numeric(10,2) NOT NULL, "used_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7b764938468b7649471720e67a1" UNIQUE ("coupon_id", "booking_id"), CONSTRAINT "PK_5727b2e426ee3e63c3f5e200e61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discount_type_enum" AS ENUM('percentage', 'fixed_amount')`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_status_enum" AS ENUM('active', 'inactive', 'expired')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying NOT NULL, "description" text, "discount_type" "public"."coupons_discount_type_enum" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "minimum_order_amount" numeric(10,2), "maximum_discount_amount" numeric(10,2), "usage_limit" integer, "usage_count" integer NOT NULL DEFAULT '0', "user_usage_limit" integer NOT NULL DEFAULT '1', "valid_from" TIMESTAMP NOT NULL, "valid_until" TIMESTAMP NOT NULL, "applicable_user_types" json, "applicable_routes" json, "status" "public"."coupons_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."commissions_status_enum" AS ENUM('pending', 'approved', 'paid')`);
        await queryRunner.query(`CREATE TABLE "commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "payment_id" uuid NOT NULL, "booking_amount" numeric(10,2) NOT NULL, "commission_rate" numeric(5,2) NOT NULL, "commission_amount" numeric(10,2) NOT NULL, "status" "public"."commissions_status_enum" NOT NULL DEFAULT 'pending', "approved_at" TIMESTAMP, "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2701379966e2e670bb5ff0ae78e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('credit_card', 'debit_card', 'bank_transfer', 'wallet', 'cash')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "payer_id" uuid NOT NULL, "company_id" uuid, "payment_method" "public"."payments_payment_method_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "stripe_payment_intent_id" character varying, "stripe_customer_id" character varying, "stripe_payment_method_id" character varying, "payment_status" "public"."payments_payment_status_enum" NOT NULL DEFAULT 'pending', "failure_reason" text, "paid_at" TIMESTAMP, "failed_at" TIMESTAMP, "refunded_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_fare_used_enum" AS ENUM('min_fare', 'original_fare', 'sale_fare')`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_booking_status_enum" AS ENUM('pending', 'confirmed', 'assigned', 'in_auction', 'auction_awarded', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_payment_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_reference" character varying(20) NOT NULL, "user_id" uuid NOT NULL, "company_id" uuid, "route_fare_id" uuid NOT NULL, "assigned_car_id" uuid, "assigned_driver_id" uuid, "passenger_name" character varying NOT NULL, "passenger_phone" character varying(20) NOT NULL, "passenger_email" character varying, "passenger_count" integer NOT NULL DEFAULT '1', "needs_infant_seat" boolean NOT NULL DEFAULT false, "needs_child_seat" boolean NOT NULL DEFAULT false, "needs_wheelchair_access" boolean NOT NULL DEFAULT false, "needs_medical_equipment" boolean NOT NULL DEFAULT false, "special_instructions" text, "pickup_datetime" TIMESTAMP NOT NULL, "pickup_address" text NOT NULL, "dropoff_address" text NOT NULL, "fare_used" "public"."bookings_fare_used_enum" NOT NULL DEFAULT 'sale_fare', "base_amount" numeric(10,2) NOT NULL, "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "coupon_id" uuid, "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "booking_status" "public"."bookings_booking_status_enum" NOT NULL DEFAULT 'pending', "payment_status" "public"."bookings_payment_status_enum" NOT NULL DEFAULT 'pending', "actual_pickup_time" TIMESTAMP, "actual_dropoff_time" TIMESTAMP, "actual_distance_km" numeric(8,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5ba137683172608bf22d69538a0" UNIQUE ("booking_reference"), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."companies_company_type_enum" AS ENUM('affiliate', 'b2b')`);
        await queryRunner.query(`CREATE TYPE "public"."companies_status_enum" AS ENUM('pending', 'approved', 'rejected', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "company_name" character varying NOT NULL, "company_email" character varying NOT NULL, "company_contact_number" character varying NOT NULL, "company_type" "public"."companies_company_type_enum" NOT NULL, "company_registration_number" character varying NOT NULL, "registration_country" character varying NOT NULL, "company_representative" character varying NOT NULL, "service_area_province" character varying, "tax_id" character varying, "address" text, "city" character varying, "state" character varying, "postal_code" character varying, "country" character varying, "website" character varying, "contact_person" character varying, "status" "public"."companies_status_enum" NOT NULL DEFAULT 'pending', "commission_rate" numeric(5,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_ee0839cba07cb0c52602021ad4" UNIQUE ("user_id"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_user_type_enum" AS ENUM('customer', 'driver', 'affiliate', 'b2b', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "phone" character varying, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "user_type" "public"."users_user_type_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "email_verified" boolean NOT NULL DEFAULT false, "phone_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_type_enum" AS ENUM('credit_card', 'debit_card', 'bank_transfer', 'wallet', 'cash')`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."payment_methods_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."earnings_earnings_type_enum" AS ENUM('booking_commission', 'auction_win', 'referral_bonus', 'platform_bonus')`);
        await queryRunner.query(`CREATE TYPE "public"."earnings_status_enum" AS ENUM('pending', 'processed', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "earnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "booking_id" uuid, "payment_id" uuid, "payout_id" uuid, "earnings_type" "public"."earnings_earnings_type_enum" NOT NULL, "gross_amount" numeric(10,2) NOT NULL, "commission_rate" numeric(5,2) NOT NULL, "commission_amount" numeric(10,2) NOT NULL, "net_earnings" numeric(10,2) NOT NULL, "platform_fee" numeric(10,2) NOT NULL DEFAULT '0', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."earnings_status_enum" NOT NULL DEFAULT 'pending', "earned_at" TIMESTAMP, "processed_at" TIMESTAMP, "paid_at" TIMESTAMP, "notes" text, "reference_number" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_32821f77c2546a1d53f674fe83f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_payout_method_enum" AS ENUM('bank_transfer', 'paypal', 'stripe', 'wire_transfer', 'check')`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_status_enum" AS ENUM('pending', 'requested', 'approved', 'processing', 'paid', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "total_amount" numeric(10,2) NOT NULL, "fee_amount" numeric(10,2) NOT NULL DEFAULT '0', "net_amount" numeric(10,2) NOT NULL, "payout_method" "public"."payouts_payout_method_enum" NOT NULL, "status" "public"."payouts_status_enum" NOT NULL DEFAULT 'pending', "payout_reference" character varying(100) NOT NULL, "period_start" TIMESTAMP NOT NULL, "period_end" TIMESTAMP NOT NULL, "earnings_count" integer NOT NULL, "bank_account_details" text, "external_transaction_id" character varying, "requested_at" TIMESTAMP, "approved_at" TIMESTAMP, "processed_at" TIMESTAMP, "paid_at" TIMESTAMP, "failure_reason" text, "admin_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0976e56c5d6d39752dfbcda3ccf" UNIQUE ("payout_reference"), CONSTRAINT "PK_76855dc4f0a6c18c72eea302e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."settings_setting_type_enum" AS ENUM('string', 'number', 'boolean', 'json')`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "setting_key" character varying NOT NULL, "setting_value" text NOT NULL, "setting_type" "public"."settings_setting_type_enum" NOT NULL DEFAULT 'string', "description" text, "is_public" boolean NOT NULL DEFAULT false, "updated_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "updaterId" uuid, CONSTRAINT "UQ_35690f287c60414f4b63614a006" UNIQUE ("setting_key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cms_pages_page_type_enum" AS ENUM('page', 'blog', 'help', 'legal')`);
        await queryRunner.query(`CREATE TYPE "public"."cms_pages_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "cms_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "meta_title" character varying, "meta_description" text, "content" text NOT NULL, "featured_image_url" character varying(500), "page_type" "public"."cms_pages_page_type_enum" NOT NULL DEFAULT 'page', "status" "public"."cms_pages_status_enum" NOT NULL DEFAULT 'draft', "sort_order" integer NOT NULL DEFAULT '0', "is_in_menu" boolean NOT NULL DEFAULT false, "menu_title" character varying, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_164bf011d905e86e677bc86a1e9" UNIQUE ("slug"), CONSTRAINT "PK_a6bd4d97252f8f122d34bc6bce6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auction_bids_status_enum" AS ENUM('active', 'withdrawn', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "auction_bids" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bid_reference" character varying(20) NOT NULL, "auction_id" uuid NOT NULL, "company_id" uuid NOT NULL, "bidder_user_id" uuid NOT NULL, "bid_amount" numeric(10,2) NOT NULL, "estimated_completion_time" TIMESTAMP, "additional_services" text, "notes" text, "proposed_driver_id" uuid, "proposed_car_id" uuid, "status" "public"."auction_bids_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_747a1dbcec0c03e479da9fc3a16" UNIQUE ("bid_reference"), CONSTRAINT "PK_75fb5ac3cf131789bf7c5181efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auction_activities_activity_type_enum" AS ENUM('created', 'started', 'bid_placed', 'bid_withdrawn', 'bid_updated', 'closed', 'awarded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "auction_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auction_id" uuid NOT NULL, "activity_type" "public"."auction_activities_activity_type_enum" NOT NULL, "user_id" uuid, "company_id" uuid, "bid_id" uuid, "previous_value" numeric(10,2), "new_value" numeric(10,2), "notes" text, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f2f143a52c7a299449e7bdbec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auctions_status_enum" AS ENUM('draft', 'active', 'closed', 'awarded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "auctions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auction_reference" character varying(20) NOT NULL, "booking_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "auction_start_time" TIMESTAMP NOT NULL, "auction_end_time" TIMESTAMP NOT NULL, "minimum_bid_amount" numeric(10,2) NOT NULL, "reserve_price" numeric(10,2), "status" "public"."auctions_status_enum" NOT NULL DEFAULT 'draft', "winning_bid_id" uuid, "winner_company_id" uuid, "awarded_at" TIMESTAMP, "awarded_by" uuid, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_073e4d544277a9f22d276ee1f0e" UNIQUE ("auction_reference"), CONSTRAINT "REL_6c542becb4da4933ceb61c00e6" UNIQUE ("winning_bid_id"), CONSTRAINT "PK_87d2b34d4829f0519a5c5570368" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "car_images" ADD CONSTRAINT "FK_b656953875307b25131f0d9af94" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_92e950a2513a79bb3fab273c92e" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_20a2df6fde367ee79c15a062537" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_2ffd7a9646568f60a28f25c5912" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_car_assignments" ADD CONSTRAINT "FK_17d9f723677808350df3073da11" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_car_assignments" ADD CONSTRAINT "FK_6c7ee8eeca506827252461d74bc" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_9b6410d2f4eabb985524faae074" FOREIGN KEY ("category_id") REFERENCES "car_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_932f58a12304c2431a1afc342f6" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_2a59fd09f9a61cfa1e422be2445" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_391794545181ad5bd68c700bffa" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_1b9fb2f1094f11eab7a80a2d513" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_72c5cb90cae74cf7ea1af139684" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_849033557800214c533304fd647" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_b57b1306fdd71690cd88300b7bb" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_02f8e8d4094492641ad95010ca1" FOREIGN KEY ("payer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_4781cf05f36ba314cdd314c0c66" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_72dbd3365e2977161f9dec96b1a" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_ce70304f05b720e3b78eaedfd72" FOREIGN KEY ("route_fare_id") REFERENCES "route_fares"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_15b9820a0adc635dae29d5886f3" FOREIGN KEY ("assigned_car_id") REFERENCES "cars"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_72b0c6a8488aa477712d46bb098" FOREIGN KEY ("assigned_driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_23ec6943dfbd6fb667f629e990b" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_ee0839cba07cb0c52602021ad4b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_b008c5e01f00abecffde114a03b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_9593d5b0867241d1cc7a7a39784" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_5f1eb8dd7699a36268ae226b1e1" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_b42a7491b7359518500a88d3126" FOREIGN KEY ("payout_id") REFERENCES "payouts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_539c61007e4ef70fcdd13cf56c3" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_86bf86727944f2818d848b2b85d" FOREIGN KEY ("updaterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD CONSTRAINT "FK_5cc8df435f4763233d3c0bc8a98" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_bids" ADD CONSTRAINT "FK_ab6d742c994d31873e68416b5ca" FOREIGN KEY ("auction_id") REFERENCES "auctions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_bids" ADD CONSTRAINT "FK_0c5eeeb034f078153ff1b76329e" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_bids" ADD CONSTRAINT "FK_f2979c31b524b989328a7b869c3" FOREIGN KEY ("bidder_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_bids" ADD CONSTRAINT "FK_549b6d36a2affcfdb4d93c61785" FOREIGN KEY ("proposed_driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_bids" ADD CONSTRAINT "FK_10ad1ff2390e083108a4a0e07db" FOREIGN KEY ("proposed_car_id") REFERENCES "cars"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_activities" ADD CONSTRAINT "FK_36823c30bf1020b20729045dba8" FOREIGN KEY ("auction_id") REFERENCES "auctions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_activities" ADD CONSTRAINT "FK_611dcf17e29d366bdd33896c1da" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_activities" ADD CONSTRAINT "FK_68adcbf9a3ab736d8ed576bfe92" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auction_activities" ADD CONSTRAINT "FK_2e5e737374f9ca3bc7bc6b4a7de" FOREIGN KEY ("bid_id") REFERENCES "auction_bids"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_97f3c588515932be75ef8fccf2c" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_7821198314c43037b20b258626c" FOREIGN KEY ("winner_company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_d698a96760648bed2fbcba1f6f5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_327a5f5a60a7a36584c523b7561" FOREIGN KEY ("awarded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auctions" ADD CONSTRAINT "FK_6c542becb4da4933ceb61c00e63" FOREIGN KEY ("winning_bid_id") REFERENCES "auction_bids"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_6c542becb4da4933ceb61c00e63"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_327a5f5a60a7a36584c523b7561"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_d698a96760648bed2fbcba1f6f5"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_7821198314c43037b20b258626c"`);
        await queryRunner.query(`ALTER TABLE "auctions" DROP CONSTRAINT "FK_97f3c588515932be75ef8fccf2c"`);
        await queryRunner.query(`ALTER TABLE "auction_activities" DROP CONSTRAINT "FK_2e5e737374f9ca3bc7bc6b4a7de"`);
        await queryRunner.query(`ALTER TABLE "auction_activities" DROP CONSTRAINT "FK_68adcbf9a3ab736d8ed576bfe92"`);
        await queryRunner.query(`ALTER TABLE "auction_activities" DROP CONSTRAINT "FK_611dcf17e29d366bdd33896c1da"`);
        await queryRunner.query(`ALTER TABLE "auction_activities" DROP CONSTRAINT "FK_36823c30bf1020b20729045dba8"`);
        await queryRunner.query(`ALTER TABLE "auction_bids" DROP CONSTRAINT "FK_10ad1ff2390e083108a4a0e07db"`);
        await queryRunner.query(`ALTER TABLE "auction_bids" DROP CONSTRAINT "FK_549b6d36a2affcfdb4d93c61785"`);
        await queryRunner.query(`ALTER TABLE "auction_bids" DROP CONSTRAINT "FK_f2979c31b524b989328a7b869c3"`);
        await queryRunner.query(`ALTER TABLE "auction_bids" DROP CONSTRAINT "FK_0c5eeeb034f078153ff1b76329e"`);
        await queryRunner.query(`ALTER TABLE "auction_bids" DROP CONSTRAINT "FK_ab6d742c994d31873e68416b5ca"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP CONSTRAINT "FK_5cc8df435f4763233d3c0bc8a98"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_86bf86727944f2818d848b2b85d"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_539c61007e4ef70fcdd13cf56c3"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_b42a7491b7359518500a88d3126"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_5f1eb8dd7699a36268ae226b1e1"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_9593d5b0867241d1cc7a7a39784"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_b008c5e01f00abecffde114a03b"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_ee0839cba07cb0c52602021ad4b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_23ec6943dfbd6fb667f629e990b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_72b0c6a8488aa477712d46bb098"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_15b9820a0adc635dae29d5886f3"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_ce70304f05b720e3b78eaedfd72"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_72dbd3365e2977161f9dec96b1a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_4781cf05f36ba314cdd314c0c66"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_02f8e8d4094492641ad95010ca1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_b57b1306fdd71690cd88300b7bb"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_849033557800214c533304fd647"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_72c5cb90cae74cf7ea1af139684"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_1b9fb2f1094f11eab7a80a2d513"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_391794545181ad5bd68c700bffa"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_2a59fd09f9a61cfa1e422be2445"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_932f58a12304c2431a1afc342f6"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_9b6410d2f4eabb985524faae074"`);
        await queryRunner.query(`ALTER TABLE "driver_car_assignments" DROP CONSTRAINT "FK_6c7ee8eeca506827252461d74bc"`);
        await queryRunner.query(`ALTER TABLE "driver_car_assignments" DROP CONSTRAINT "FK_17d9f723677808350df3073da11"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_2ffd7a9646568f60a28f25c5912"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_20a2df6fde367ee79c15a062537"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_92e950a2513a79bb3fab273c92e"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63"`);
        await queryRunner.query(`ALTER TABLE "car_images" DROP CONSTRAINT "FK_b656953875307b25131f0d9af94"`);
        await queryRunner.query(`DROP TABLE "auctions"`);
        await queryRunner.query(`DROP TYPE "public"."auctions_status_enum"`);
        await queryRunner.query(`DROP TABLE "auction_activities"`);
        await queryRunner.query(`DROP TYPE "public"."auction_activities_activity_type_enum"`);
        await queryRunner.query(`DROP TABLE "auction_bids"`);
        await queryRunner.query(`DROP TYPE "public"."auction_bids_status_enum"`);
        await queryRunner.query(`DROP TABLE "cms_pages"`);
        await queryRunner.query(`DROP TYPE "public"."cms_pages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cms_pages_page_type_enum"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TYPE "public"."settings_setting_type_enum"`);
        await queryRunner.query(`DROP TABLE "payouts"`);
        await queryRunner.query(`DROP TYPE "public"."payouts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payouts_payout_method_enum"`);
        await queryRunner.query(`DROP TABLE "earnings"`);
        await queryRunner.query(`DROP TYPE "public"."earnings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."earnings_earnings_type_enum"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_user_type_enum"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TYPE "public"."companies_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."companies_company_type_enum"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_booking_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_fare_used_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "commissions"`);
        await queryRunner.query(`DROP TYPE "public"."commissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discount_type_enum"`);
        await queryRunner.query(`DROP TABLE "coupon_usage"`);
        await queryRunner.query(`DROP TABLE "cars"`);
        await queryRunner.query(`DROP TYPE "public"."cars_status_enum"`);
        await queryRunner.query(`DROP TABLE "driver_car_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."driver_car_assignments_status_enum"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_background_check_status_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TYPE "public"."reviews_status_enum"`);
        await queryRunner.query(`DROP TABLE "car_images"`);
        await queryRunner.query(`DROP TYPE "public"."car_images_image_type_enum"`);
        await queryRunner.query(`DROP TABLE "car_categories"`);
        await queryRunner.query(`DROP TYPE "public"."car_categories_status_enum"`);
        await queryRunner.query(`DROP TABLE "route_fares"`);
    }

}
