import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPublicApiSupport1753124705671 implements MigrationInterface {
    name = 'AddPublicApiSupport1753124705671'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reviews" ADD "customerName" character varying`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "featured" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "rating" integer`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "comment" text`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "basePrice" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "pricePerKm" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "pricePerHour" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "features" json`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "passengerCapacity" integer`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "luggageCapacity" integer`);
        await queryRunner.query(`ALTER TABLE "car_categories" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "fromLocation" character varying`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "toLocation" character varying`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "basePrice" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "pricePerKm" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "minimumPrice" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "estimatedDuration" integer`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "distance" numeric(8,2)`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "featured" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD "carCategoryId" uuid`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "discountType" character varying`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "discountValue" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "maxDiscount" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "minimumAmount" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "validFrom" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "validTo" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "usageLimit" integer`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "usedCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "flight_number" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_payment_method_enum" AS ENUM('ONLINE', 'CASH')`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "payment_method" "public"."bookings_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "type" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "contactEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "contactPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "contactPerson" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "position" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "region" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "publicEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "publicPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "logo" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country_code" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "preferred_language" character varying DEFAULT 'en'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "blacklisted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verification_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_expiry" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "published" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "showInMenu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cms_pages" ADD "type" character varying`);
        await queryRunner.query(`ALTER TABLE "route_fares" ADD CONSTRAINT "FK_cfa342b208870a59a5b93705ee1" FOREIGN KEY ("carCategoryId") REFERENCES "car_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "route_fares" DROP CONSTRAINT "FK_cfa342b208870a59a5b93705ee1"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "order"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "showInMenu"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "published"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "cms_pages" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_expiry"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "blacklisted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "preferred_language"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country_code"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "logo"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "publicPhone"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "publicEmail"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "position"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "contactPerson"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "contactPhone"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "contactEmail"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "flight_number"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "usedCount"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "usageLimit"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "validTo"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "validFrom"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "minimumAmount"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "maxDiscount"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "discountValue"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "discountType"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "carCategoryId"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "featured"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "estimatedDuration"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "minimumPrice"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "pricePerKm"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "basePrice"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "toLocation"`);
        await queryRunner.query(`ALTER TABLE "route_fares" DROP COLUMN "fromLocation"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "luggageCapacity"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "passengerCapacity"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "features"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "pricePerHour"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "pricePerKm"`);
        await queryRunner.query(`ALTER TABLE "car_categories" DROP COLUMN "basePrice"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "comment"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "featured"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "customerName"`);
    }

}
