version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: novaride-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novaride111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./server
    container_name: novaride-server
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=novaride111
      - JWT_SECRET=your-very-strong-production-secret-key
      - JWT_EXPIRES_IN=24h
      - PORT=3005
      - NODE_ENV=production

  server-commands:
    build:
      context: ./server
      target: builder
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=novaride111
    command: sh -c "npm run migration:run && npm run seed && node dist/main"

  client:
    build:
      context: ./client
    container_name: novaride-client
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data: